### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by VikDAnalyst** [VikDAnalyst/Premier-Project---Hamoye#1]
We can drop ideas about the dataset

**Comment by VikDAnalyst** [comment]
We can start to drop updates on where we are!

**Comment by Elohorokpako** [comment]
I just completed my part. Reduced about 300 columns in the dataset. I'd include my codes in the branch

**Comment by VikDAnalyst** [comment]
> I just completed my part. Reduced about 300 columns in the dataset. I'd include my codes in the branch

Okay! Well done Bro

**Comment by Elohorokpako** [comment]
Issue resolved
